//* App Actions
export const SWITCH_MODE = "SWITCH_MODE";
export const CHANGE_SCREEN_SIZE = "CHANGE_SCREEN_SIZE";

//* Games Actions
export const FETCH_GAMES = "FETCH_GAMES";
export const FETCH_GAMES_SUCCESS = "FETCH_GAMES_SUCCESS";
export const FETCH_GAMES_NEXT = "FETCH_GAMES_NEXT";
export const FETCH_GAMES_NOMORE = "FETCH_GAMES_NOMORE";
export const RESET_GAMES_DATA = "RESET_GAMES_DATA";

//* Game Actions
export const FETCH_GAME = "FETCH_GAME";

//* Genre Actions
export const FETCH_GENRES = "FETCH_GENRES";
export const FETCH_GENRES_SUCCESS = "FETCH_GENRES_SUCCESS";
export const FETCH_GENRE_DESCRIPTION = "FETCH_GENRE_DESCRIPTION";

//* User Actions
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const FETCH_USER_COLLECTION_SUCCESS = "FETCH_USER_COLLECTION_SUCCESS";
export const TOGGLE_COLLECTION = "TOGGLE_COLLECTION";
export const TOGGLE_COLLECTION_SUCCESS = "TOGGLE_COLLECTION_SUCCESS";
